// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Edbr9lBC5ElNEPcBIBriO7LFObf3FA8',
    appId: '1:968363243988:web:05ce6381d69f189d5f7e41',
    messagingSenderId: '968363243988',
    projectId: 'armariointeligente-b99a5',
    authDomain: 'armariointeligente-b99a5.firebaseapp.com',
    storageBucket: 'armariointeligente-b99a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz9C10v9SBDBl5YvJtrfDZssZ2phDw5YM',
    appId: '1:968363243988:android:8a7b3e69b52d5e915f7e41',
    messagingSenderId: '968363243988',
    projectId: 'armariointeligente-b99a5',
    storageBucket: 'armariointeligente-b99a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAStaVao00gtKSfJXjeldaRn_COR8wfjg4',
    appId: '1:968363243988:ios:1e1d11f1dda00d4a5f7e41',
    messagingSenderId: '968363243988',
    projectId: 'armariointeligente-b99a5',
    storageBucket: 'armariointeligente-b99a5.firebasestorage.app',
    iosBundleId: 'com.example.armarioInteligente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAStaVao00gtKSfJXjeldaRn_COR8wfjg4',
    appId: '1:968363243988:ios:1e1d11f1dda00d4a5f7e41',
    messagingSenderId: '968363243988',
    projectId: 'armariointeligente-b99a5',
    storageBucket: 'armariointeligente-b99a5.firebasestorage.app',
    iosBundleId: 'com.example.armarioInteligente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Edbr9lBC5ElNEPcBIBriO7LFObf3FA8',
    appId: '1:968363243988:web:99dd8edfdbd4d30f5f7e41',
    messagingSenderId: '968363243988',
    projectId: 'armariointeligente-b99a5',
    authDomain: 'armariointeligente-b99a5.firebaseapp.com',
    storageBucket: 'armariointeligente-b99a5.firebasestorage.app',
  );
}
